'use client';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { useState, useEffect } from 'react';
import Sidebar from "./components/Sidebar";
import UserBar from "./components/UserBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata = {
  title: "Janmitra Admin Panel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [isSidebarOpen, setIsSidebarOpen] = useState(false);
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const [mobile, setMobile] = useState('');
  const [password, setPassword] = useState('');


  useEffect(() => {
    const token = localStorage.getItem('token');
    if (token) setIsAuthenticated(true);
  }, []);

  // Prevent scroll when sidebar is open on small screens
  useEffect(() => {
    if (isSidebarOpen && window.innerWidth < 768) {
      document.body.classList.add('overflow-hidden');
    } else {
      document.body.classList.remove('overflow-hidden');
    }
  }, [isSidebarOpen]);

  const toggleSidebar = () => setIsSidebarOpen(prev => !prev);

  const handleLogout = () => {
    localStorage.removeItem('token');
    setIsAuthenticated(false);
  };

  const handleLogin = async () => {
    try {
      const response = await fetch('http://localhost:5000/api/auth/login', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          mobile: mobile,
          password: password,
        }),
      });

      if (!response.ok) {
        throw new Error('Invalid credentials');
      }

      const data = await response.json();

      // Store token
      localStorage.setItem('token', data.token);

      // Optionally store user info
      localStorage.setItem('user', JSON.stringify(data.user));

      setIsAuthenticated(true);
    } catch (err) {
      alert(err.message || 'Login failed');
    }
  };


  return (
    <html lang="en">
      <title>Janmitra Admin Panel</title>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {isAuthenticated ? (
          <div className="flex h-screen overflow-hidden">
            <Sidebar isOpen={isSidebarOpen} toggleSidebar={toggleSidebar} />
            <div className="flex flex-col flex-1 h-full">
              <UserBar title="जनमित्र Admin Panel" onLogout={handleLogout} onToggleSidebar={toggleSidebar} />
              <main className="flex-1 overflow-y-auto p-4 bg-gray-100">
                {children}
              </main>
            </div>
          </div>
        ) : (
          <div className="flex items-center justify-center min-h-screen bg-gray-100 px-4">
            <div className="bg-white p-6 rounded shadow-md w-full max-w-sm">
              <h2 className="text-xl font-semibold mb-4 text-center">Admin Login</h2>
              <input
                type="text"
                placeholder="Mobile"
                className="w-full border p-2 mb-3 rounded"
                value={mobile}
                onChange={(e) => setMobile(e.target.value)}
              />
              <input
                type="password"
                placeholder="Password"
                className="w-full border p-2 mb-3 rounded"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
              />

              <button
                onClick={handleLogin}
                className="w-full bg-blue-600 text-white p-2 rounded hover:bg-blue-700 transition"
              >
                Login
              </button>
            </div>
          </div>
        )}
      </body>
    </html>
  );
}
